### ISSUE TITLE
What does "will be reset" mean?

### ISSUE THREAD

**Issue by benlk** [wp-cli/role-command#35]
This is a docs question:

- Does 'reset' add back permissions that were removed?
- Does 'reset' delete capabilities from the default Core permissions list that were added to this role?
- Does 'reset' delete custom capabilities from plugins or themes that were added to this role?

**Comment by schlessera** [comment]
It basically uses WordPress' `populate_roles()` function to put a given role back into the state that it normally is when you have a fresh WordPress install. So it will remove caps that were added and put back in caps that were removed.

**Comment by benlk** [comment]
So then the answer to each of my three questions is "yes". Neat!

What file should I file a PR editing to update the docs?

**Comment by schlessera** [comment]
These additional details would go in here: https://github.com/wp-cli/role-command/blob/master/src/Role_Command.php#L247
